
############################################################################
############################################################################
###                                                                      ###
###          A MAJORITY OF THIS CODE WAS GENERATED BY CLAUDE.AI          ###
###                                                                      ###
############################################################################
############################################################################


###  Most of the code seen here was generated with an LLM. Edits include      
###  converting the code into a class and saving information as Pandas data   
###  frames                                                                
 

import pandas as pd
import numpy as np
from scipy.io import FortranFile

class ExtractTreeInfo:

    
    def __init__(self, 
                 tree_file):
        
        '''
        
        The initializer function for the class which will be called upon in
        later functions.
        
        Inputs:
            self (self object):  This is the self object that will be used
            throughout the class.
            
            tree_file (str):  The file path of where your tree.dat file is 
            stored.
            
        Outputs:
            self.tree_header (Pandas data frame):  The header information from
            the Fortran binary file. To read more about the specifics of the
            columns, please read the docstrings in find_tree_info().
            
            self.tree_info (Pandas data frame):  This data frame contains
            information on the host halo, subhalos, and father and son halos
            from the Fortran binary file. To read more details on the columns,
            please read the docstrings in find_tree_info().
        
        '''
        
    

        self.data_path = tree_file
        self.tree_header = pd.DataFrame()
        self.tree_info = pd.DataFrame()
        
        # Ensuring that when calling this class, the ititializer also runs the
        # main function, find_tree_info():
        self.find_tree_info()
        
        
        # These lines were created by Claude.AI. As of writing this, I am not 
        # sure if I actually need these or not. I will keep them here for now
        # until I confirm if these variables are needed.
        self.galdir     = "./"
        self.debug      = False
        self.star       = False
        self.subhalo    = False
        self.separate   = False
        self.contaminated   = False
        self.contam_arg     = False
        self.mmin       = 1.0
        self.mmax       = 1e17
        self.omega_m    = 0.272
        self.omega_l    = 0.728
        self.omega_k    = 0.0
        self.h0         = 70.4
        
    def find_tree_info(self):
        
        '''
        
        The main function of ExtractTreeInfo. This function will read in the
        tree.dat file and extract the host halo, its subhalos, and its father
        and son halos. 
        
        Inputs:
            self (self object):  The self object from the initializer function
            that will be called on.
            
        Outputs:
            self.tree_header (Pandas data fraem):  
            
        
        '''
        
    
        with FortranFile(self.data_path, 'r') as f:
        
            # Header
            nsteps = f.read_ints(dtype=np.int32)[0]
            print(f"{nsteps} steps")
        
            halo_counts    = f.read_ints(dtype=np.int32)          # nb_of_halos + nb_of_subhalos interleaved
            nb_of_halos    = halo_counts[:nsteps]
            nb_of_subhalos = halo_counts[nsteps:]
        
            aexp      = f.read_reals(dtype=np.float32)            # Expansion factor at each step
            omega_t   = f.read_reals(dtype=np.float32)            # Omega_matter at each step
            age_univ  = f.read_reals(dtype=np.float32)            # Age of universe at each step
            
            self.tree_header = pd.DataFrame({
                
                "Number of Halos": nb_of_halos,
                "Number of Subhalos": nb_of_subhalos,
                "A Expansion": aexp,
                "Omega T": omega_t,
                "Age of Universe (Standard Time Unit)": age_univ
                
                })
        
        
            # ── Per-step / per-halo loop ─────────────────────────────────────────────
            idselec_tmp      = None
            idmainfather_tmp = None
            finsitu_tmp      = None
            mselec_tmp       = None
            minsitu_tmp      = None
            ok               = None
            
            rows = []
        
            for istep in range(1, nsteps + 1):
                ntot = nb_of_halos[istep - 1] + nb_of_subhalos[istep - 1]
        
                if istep == 1:
                    idselec_tmp      = np.zeros(ntot, dtype=np.int32)
                    idmainfather_tmp = np.zeros(ntot, dtype=np.int32)
                    finsitu_tmp      = np.zeros(ntot, dtype=np.float32)
                    mselec_tmp       = np.zeros(ntot, dtype=np.float32)
                    minsitu_tmp      = np.zeros(ntot, dtype=np.float32)
                    ok               = np.zeros(ntot, dtype=bool)
        
                # nfile(istep) would come from a list read elsewhere — placeholder here
                nfile_step = istep  # replace with actual nfile array if available
                nchar      = str(nfile_step).zfill(5)
                repository = f"{self.tree_path}/GAL_{nchar}"
        
                for j in range(1, ntot + 1):
                    mynumber = f.read_ints(dtype=np.int32)[0]    # Halo identity
                    BushID   = f.read_ints(dtype=np.int32)[0]    # Tree identity
                    mystep   = f.read_ints(dtype=np.int32)[0]    # Step of the tree
        
                    level, hosthalo, hostsub, nbsub, nextsub = f.read_ints(dtype=np.int32)
                    # level    : 1=main halo, 2=sub-halo, 3=sub-sub-halo, …
                    # hosthalo : id of the level-1 main halo
                    # hostsub  : id of the level-1 host of this halo
                    # nbsub    : number of level+1 subhalos of this halo
                    # nextsub  : id of first sub-halo, or next same-level sister, etc.
        
                    m    = f.read_reals(dtype=np.float32)[0]     # Halo mass [1e11 Msun], excl. substructure
                    macc = f.read_reals(dtype=np.float32)[0]     # Mass variation between steps [1e11 Msun]
        
                    px, py, pz = f.read_reals(dtype=np.float32) # Position [Lbox/2 proper Mpc]
                    vx, vy, vz = f.read_reals(dtype=np.float32) # Velocity [km/s]
                    Lx, Ly, Lz = f.read_reals(dtype=np.float32) # Angular momentum [1e11 Msun·km/s·Mpc]
        
                    r, ra, rb, rc = f.read_reals(dtype=np.float32)  # Radius & semi-major axes [proper Mpc]
        
                    ek, ep, et = f.read_reals(dtype=np.float32) # Kinetic, gravitational, internal energy
                    spin       = f.read_reals(dtype=np.float32)[0]  # Bullock spin parameter
        
                    # Fathers
                    nb_of_fathers = f.read_ints(dtype=np.int32)[0]
                    if nb_of_fathers > 0:
                        idfather = f.read_ints(dtype=np.int32)       # ids of father halos
                        mfather  = f.read_reals(dtype=np.float32)    # mass contribution [%]
                    else:
                        idfather = np.array([], dtype=np.int32)
                        mfather  = np.array([], dtype=np.float32)
        
                    if j != mynumber:
                        print(f"Warning: index mismatch j={j}, mynumber={mynumber}")
        
                    # Sons
                    nb_of_sons = f.read_ints(dtype=np.int32)[0]
                    if nb_of_sons > 0:
                        idson = f.read_ints(dtype=np.int32)          # ids of son halos
                    else:
                        idson = np.array([], dtype=np.int32)
        
                    # Two blank reads (present in original Fortran)
                    f.read_record()
                    f.read_record()
                    
                    rows.append({
                        
                        "Halo ID": mynumber,
                        "Tree ID": BushID,
                        "Time Step of Tree": mystep,
                        "Halo Level": level,
                        "Host Halo ID": hosthalo,
                        "Host Subhalo ID": hostsub,
                        "Total Number of Halos in Host": nbsub,
                        "First Subhalo/Sister Halo": nextsub,
                        "Halo Mass (Standard Mass Unit)": m,
                        "Mass Variation (Standard Mass Unit)": macc,
                        "X Position of Host Halo (Mpc)": px,
                        "Y Position of Host Halo (Mpc)": py,
                        "Z Position of Host Halo (Mpc)": pz,
                        "X Velocity of Host Halo (km/s)": vx,
                        "Y Velocity of Host Halo (km/s)": vy,
                        "Z Velocity of Host Halo (km/s)": vz,
                        "X Angular Momentum of Host Halo (Standard Mass Unit * km/s * Mpc)": Lx,
                        "Y Angular Momentum of Host Halo (Standard Mass Unit * km/s * Mpc)": Ly,
                        "Z Angular Momentum of Host Halo (Standard Mass Unit * km/s * Mpc)": Lz,
                        "Radius of Host Halo (Mpc)": r,
                        "A Semi-Major Axis of Host Halo (Mpc)": ra,
                        "B Semi-Major Axis of Host Halo (Mpc)": rb,
                        "C Semi-Major Axis of Host Halo (Mpc)": rc,
                        "Kinetic Energy of Host Halo (J)": ek,
                        "Gravitational Potential Energy of Host Halo (J)": ep,
                        "Internal Energy of Host Halo (J)": et,
                        "Bullock Spin of Host Halo": spin,
                        "Father Halo ID": idfather,
                        "Mass Contribution of Father Halo": mfather,
                        "Son Halo ID": idson
                        
                        })
            
            self.tree_info = pd.DataFrame(rows)
                
            return self.tree_header, self.tree_info

